### ISSUE TITLE
We should restore the plain object annotation on ReactElement and DOMElement

### ISSUE THREAD

**Issue by ivmarkov** [GWTReact/gwt-react#13]
Currently, the GWT compiler in superdev mode issues strange cast exceptions when a local variable of type ReactElement is assigned a value.

I think the reason is as follows:

Currently, both ReactElement and DOMElement are classes and have the following annotation:
`@JsType(isNative = true)`

However, the correct annotation should be:
`@JsType(isNative = true, namespace = JsPackage.GLOBAL, name = "Object")`

Why? Because ReactElement and DOMElement are plain JS objects. In other words, they do not have a prototype chain, and "instanceof" on ReactElement will return "object" rather than "ReactElement".

This is properly documented in React here:
* https://reactjs.org/blog/2015/12/18/react-components-elements-and-instances.html
** Emphasis mine: "An element is a *plain* object describing a component instance or DOM node and its desired properties"
* Also in the JavaDoc comment of createElement: 
```
/**
 * Factory method to create a new React element. This no longer adheres to
 * the class pattern, so do not use new to call it. Also, no instanceof check
 * will work. Instead test $$typeof field against Symbol.for('react.element') to check
 * if something is a React Element.
 *
 * @param {*} type
 * @param {*} key
 * @param {string|object} ref
 * @param {*} self A *temporary* helper to detect places where `this` is
 * different from the `owner` when React.createElement is called, so that we
 * can warn. We want to get rid of owner and replace string `ref`s with arrow
 * functions, and as long as `this` and owner are the same, there will be no
 * change in behavior.
 * @param {*} source An annotation object (added by a transpiler or otherwise)
 * indicating filename, line number, and/or other information.
 * @param {*} owner
 * @param {*} props
 * @internal
 */
var ReactElement = function(type, key, ref, self, source, owner, props)
```

**Comment by ivmarkov** [comment]
Maybe another viable alternative is to turn ReactElement and DOMElement into interfaces, because, as per the JSInterop spec, interfaces do not have an "instanceof" semantics. That would require to Move the type, props and key fields into getter properties - abreaking change. This however corresponds better to the fact that ReactElement is immutable (Object.freeze is being called right before a new ReactElement instance is returned).

**Comment by ivmarkov** [comment]
Not to put too much pressure here, but the issue is rather severe and is hitting us badly. I'm a bit surprised that you don't experience similar problems with GWT superdevmode.

**Comment by pstockley** [comment]
I am OK with the change, I just wanted to do some testing on our production codebase before committing. It's just unfortunate timing as we are just finalizing our monthly release this week so I won't have time until next week.

It's strange, that we have never run into this issue. Looking at our code base, we don't assign to variables of that type. We return these types from functions all the time but no assignments.
